{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Motivation\n",
        "\n",
        "> 📖 Read the full article: [Manim: Create Mathematical Animations Like 3Blue1Brown Using Python](https://codecut.ai/manim-mathematical-animations-python/)\n",
        "\n",
        "\n",
        "Have you ever struggled with math concepts in a machine learning algorithm and turned to 3Blue1Brown as a learning resource? 3Blue1Brown is a popular math YouTube channel created by Grant Sanderson, known for exceptional explanations and stunning animations.\n",
        "\n",
        "What if you could create similar animations to explain data science concepts to your teammates, managers, or followers?\n",
        "\n",
        "Grant developed a Python package called **Manim** that enables you to create mathematical animations or pictures using Python. In this article, you will learn how to create beautiful mathematical animations using Manim.\n",
        "\n",
        "> 💻 **Get the Code**: The complete source code and Jupyter notebook for this tutorial are available on [GitHub](https://github.com/khuyentran1401/codecut-blog/blob/main/manim_mathematical_animations.ipynb). Clone it to follow along!\n",
        "\n",
        "## What is Manim?\n",
        "\n",
        "Manim is an animation engine for creating precise, explanatory math videos. Note that there are two versions of Manim:\n",
        "\n",
        "1. [The original version created by Grant Sanderson](https://github.com/3b1b/manim)\n",
        "2. [The community-maintained version](https://github.com/ManimCommunity/manim)\n",
        "\n",
        "Since the Manim Community version is updated more frequently and better tested, we'll use it for this tutorial.\n",
        "\n",
        "To install the dependencies for the package, visit the [Documentation](https://docs.manim.community/en/stable/installation.html). After the dependencies are installed, run:\n",
        "\n",
        "```bash\n",
        "pip install manim\n",
        "```\n",
        "\n",
        "\n",
        "## Create a Blue Square that Grows from the Center\n",
        "\n",
        "We'll start by creating a blue square that grows from the center:\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class GrowingSquare(Scene):\n",
        "    def construct(self):\n",
        "        square = Square(color=BLUE, fill_opacity=0.5)\n",
        "        self.play(GrowFromCenter(square))\n",
        "        self.wait()\n",
        "```\n",
        "\n",
        "The code leverages four key Manim elements to produce the animation.\n",
        "\n",
        "- **Scene**: [Base class](https://docs.manim.community/en/stable/reference.html#scenes) providing animation infrastructure via `construct()` and `play()` methods\n",
        "- **Square(color, fill_opacity)**: [Mobject](https://docs.manim.community/en/stable/reference.html#mobjects) for creating squares with specified stroke color and fill transparency\n",
        "- **GrowFromCenter**: [Growth animation](https://docs.manim.community/en/stable/reference.html#animations) starting from the object's center\n",
        "- **wait()**: 1-second pause in animation timeline\n",
        "\n",
        "Save the script above as `start.py`. Now run the command below to generate a video for the script:\n",
        "\n",
        "```bash\n",
        "manim -p -ql start.py GrowingSquare\n",
        "```\n",
        "\n",
        "A video called `GrowingSquare.mp4` will be saved in your local directory. You should see a blue square growing from the center.\n",
        "\n",
        "![Image showing a blue square growing from the center](https://codecut.ai/wp-content/uploads/2025/11/GrowingSquare_ManimCE_v0.19.0.gif)\n",
        "\n",
        "**Explanation of the options:**\n",
        "\n",
        "- `-p`: play the video once it finishes generating\n",
        "- `-ql`: generate a video with low quality\n",
        "\n",
        "To generate a video with high quality, use `-qh` instead.\n",
        "\n",
        "To create a GIF instead of a video, add `--format=gif` to the command:\n",
        "\n",
        "```bash\n",
        "manim -p -ql --format=gif start.py GrowingSquare\n",
        "```\n",
        "\n",
        "## Turn a Square into a Circle\n",
        "\n",
        "Creating a square alone is not that exciting. Let's transform the square into a circle using the `Transform` animation.\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class SquareToCircle(Scene):\n",
        "    def construct(self):\n",
        "        circle = Circle()\n",
        "        circle.set_fill(PINK, opacity=0.5)\n",
        "\n",
        "        square = Square()\n",
        "        square.rotate(PI / 4)\n",
        "\n",
        "        self.play(Create(square))\n",
        "        self.play(Transform(square, circle))\n",
        "        self.play(FadeOut(square))\n",
        "```\n",
        "\n",
        "![Image showing a square transforming into a circle](https://codecut.ai/wp-content/uploads/2025/11/SquareToCircle_ManimCE_v0.19.0.gif)\n",
        "\n",
        "This code demonstrates creating shapes, styling them, and applying different animation effects.\n",
        "\n",
        "- **Circle**: Creates a circular shape\n",
        "- **set_fill(color, opacity)**: Sets the fill color and transparency (0.5 = 50% transparent)\n",
        "- **rotate(angle)**: Rotates the object by an angle (PI/4 = 45 degrees)\n",
        "- **Create**: Animation that draws the shape onto the screen\n",
        "- **Transform**: Smoothly morphs one shape into another\n",
        "- **FadeOut**: Makes the object gradually disappear\n",
        "\n",
        "Find a comprehensive list of shapes in the [Manim geometry documentation](https://docs.manim.community/en/stable/reference/manim.mobject.geometry.html#module-manim.mobject.geometry).\n",
        "\n",
        "## Customize Manim\n",
        "\n",
        "If you don't want the background to be black, you can change it to white using `self.camera.background_color`:\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class CustomBackground(Scene):\n",
        "    def construct(self):\n",
        "        self.camera.background_color = WHITE\n",
        "\n",
        "        square = Square(color=BLUE, fill_opacity=0.5)\n",
        "        circle = Circle(color=RED, fill_opacity=0.5)\n",
        "\n",
        "        self.play(Create(square))\n",
        "        self.wait()\n",
        "        self.play(Transform(square, circle))\n",
        "        self.wait()\n",
        "```\n",
        "\n",
        "![Image showing a white background](https://codecut.ai/wp-content/uploads/2025/11/CustomBackground_ManimCE_v0.19.0.gif)\n",
        "\n",
        "Find other ways to customize Manim in the [configuration documentation](https://docs.manim.community/en/stable/tutorials/configuration.html).\n",
        "\n",
        "\n",
        "## Write Mathematical Equations with a Moving Frame\n",
        "\n",
        "You can create animations that write mathematical equations using the `MathTex` class:\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class WriteEquation(Scene):\n",
        "    def construct(self):\n",
        "        equation = MathTex(r\"e^{i\\pi} + 1 = 0\")\n",
        "\n",
        "        self.play(Write(equation))\n",
        "        self.wait()\n",
        "```\n",
        "\n",
        "![Image showing a mathematical equation being written](https://codecut.ai/wp-content/uploads/2025/11/WriteEquation_ManimCE_v0.19.0.gif)\n",
        "\n",
        "This code demonstrates writing mathematical equations using LaTeX.\n",
        "\n",
        "- **MathTex**: Creates mathematical equations using LaTeX notation (the `r` prefix indicates a raw string for LaTeX commands)\n",
        "- **Write**: Animation that makes text appear as if being written by hand\n",
        "\n",
        "Or show step-by-step solutions to equations:\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class EquationSteps(Scene):\n",
        "    def construct(self):\n",
        "        step1 = MathTex(r\"2x + 5 = 13\")\n",
        "        step2 = MathTex(r\"2x = 8\")\n",
        "        step3 = MathTex(r\"x = 4\")\n",
        "\n",
        "        self.play(Write(step1))\n",
        "        self.wait()\n",
        "        self.play(Transform(step1, step2))\n",
        "        self.wait()\n",
        "        self.play(Transform(step1, step3))\n",
        "        self.wait()\n",
        "```\n",
        "\n",
        "![Image showing a step-by-step solution to an equation](https://codecut.ai/wp-content/uploads/2025/11/EquationSteps_ManimCE_v0.19.0.gif)\n",
        "\n",
        "Let's break down this code:\n",
        "\n",
        "- **Three equation stages**: Separate MathTex objects for each step of the solution\n",
        "- **Progressive transformation**: `Transform` morphs the first equation through intermediate and final stages\n",
        "- **Timed pauses**: `wait()` creates natural breaks between steps for a teaching pace\n",
        "\n",
        "You can also highlight specific parts of equations using frames:\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class MovingFrame(Scene):\n",
        "    def construct(self):\n",
        "        # Write equations\n",
        "        equation = MathTex(\"2x^2-5x+2\", \"=\", \"(x-2)(2x-1)\")\n",
        "\n",
        "        # Create animation\n",
        "        self.play(Write(equation))\n",
        "\n",
        "        # Add moving frames\n",
        "        framebox1 = SurroundingRectangle(equation[0], buff=.1)\n",
        "        framebox2 = SurroundingRectangle(equation[2], buff=.1)\n",
        "\n",
        "        # Create animations\n",
        "        self.play(Create(framebox1))\n",
        "\n",
        "        self.wait()\n",
        "        # Replace frame 1 with frame 2\n",
        "        self.play(ReplacementTransform(framebox1, framebox2))\n",
        "\n",
        "        self.wait()\n",
        "```\n",
        "\n",
        "![Image showing a frame highlighting different parts of an equation](https://codecut.ai/wp-content/uploads/2025/11/MovingFrame_ManimCE_v0.19.0.gif)\n",
        "\n",
        "In this code, we use the following elements:\n",
        "\n",
        "- **MathTex with multiple arguments**: Breaks the equation into separate parts that can be individually accessed and highlighted\n",
        "- **SurroundingRectangle(mobject, buff)**: Creates a box around an equation part (buff=0.1 sets the space between the box and the content)\n",
        "- **ReplacementTransform**: Smoothly moves and morphs one frame into another, replacing the first frame with the second\n",
        "\n",
        "\n",
        "## Moving and Zooming Camera\n",
        "\n",
        "You can adjust the camera and select which part of the equations to zoom in using a class inherited from `MovingCameraScene`:\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class MovingCamera(MovingCameraScene):\n",
        "    def construct(self):\n",
        "        equation = MathTex(\n",
        "            r\"\\frac{d}{dx}(x^2) = 2x\"\n",
        "        )\n",
        "\n",
        "        self.play(Write(equation))\n",
        "        self.wait()\n",
        "\n",
        "        # Zoom in on the derivative\n",
        "        self.play(\n",
        "            self.camera.frame.animate.scale(0.5).move_to(equation[0])\n",
        "        )\n",
        "        self.wait()\n",
        "```\n",
        "\n",
        "![Image showing a moving camera](https://codecut.ai/wp-content/uploads/2025/11/MovingCamera_ManimCE_v0.19.0.gif)\n",
        "\n",
        "This code shows how to zoom in on specific parts of your animation.\n",
        "\n",
        "- **MovingCameraScene**: A special scene type that allows the camera to move and zoom\n",
        "- **self.camera.frame**: Represents the camera's view that you can move and zoom\n",
        "- **animate.scale(0.5)**: Zooms in by making the camera view 50% smaller (objects appear twice as big)\n",
        "- **move_to(equation[0])**: Centers the camera on the first part of the equation\n",
        "\n",
        "## Graph\n",
        "\n",
        "You can use Manim to create annotated graphs:\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class Graph(Scene):\n",
        "    def construct(self):\n",
        "        axes = Axes(\n",
        "            x_range=[-3, 3, 1],\n",
        "            y_range=[-5, 5, 1],\n",
        "            x_length=6,\n",
        "            y_length=6,\n",
        "        )\n",
        "\n",
        "        # Add labels\n",
        "        axes_labels = axes.get_axis_labels(x_label=\"x\", y_label=\"f(x)\")\n",
        "\n",
        "        # Create a function graph\n",
        "        graph = axes.plot(lambda x: x**2, color=BLUE)\n",
        "        graph_label = axes.get_graph_label(graph, label=\"x^2\")\n",
        "\n",
        "        self.add(axes, axes_labels)\n",
        "        self.play(Create(graph))\n",
        "        self.play(Write(graph_label))\n",
        "        self.wait()\n",
        "```\n",
        "\n",
        "![Image showing a graph](https://codecut.ai/wp-content/uploads/2025/11/Graph_ManimCE_v0.19.0.png)\n",
        "\n",
        "This code shows how to create mathematical function graphs with labeled axes.\n",
        "\n",
        "- **Axes**: Creates a coordinate grid with specified ranges (e.g., x from -3 to 3, y from -5 to 5) and sizes\n",
        "- **get_axis_labels**: Adds \"x\" and \"f(x)\" labels to the coordinate axes\n",
        "- **plot(lambda x: x**2)**: Plots a mathematical function (here, x squared) as a curve on the axes\n",
        "- **get_graph_label**: Adds a label showing the function's equation next to the plotted curve\n",
        "- **self.add**: Instantly displays objects on screen without animating them in\n",
        "\n",
        "If you want to get an image of the last frame of a scene, add `-s` to the command:\n",
        "\n",
        "```bash\n",
        "manim -p -qh -s more.py Graph\n",
        "```\n",
        "\n",
        "You can also animate the process of setting up the axes:\n",
        "\n",
        "```bash\n",
        "manim -p -qh more.py Graph\n",
        "```\n",
        "\n",
        "![Image showing a graph being animated](https://codecut.ai/wp-content/uploads/2025/11/Graph_ManimCE_v0.19.0.gif)\n",
        "\n",
        "## Move Objects Together\n",
        "\n",
        "You can use `VGroup` to group different Manim objects and move them together:\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class MoveObjectsTogether(Scene):\n",
        "    def construct(self):\n",
        "        square = Square(color=BLUE)\n",
        "        circle = Circle(color=RED)\n",
        "\n",
        "        # Group objects\n",
        "        group = VGroup(square, circle)\n",
        "        group.arrange(RIGHT, buff=1)\n",
        "\n",
        "        self.play(Create(group))\n",
        "        self.wait()\n",
        "\n",
        "        # Move the entire group\n",
        "        self.play(group.animate.shift(UP * 2))\n",
        "        self.wait()\n",
        "```\n",
        "\n",
        "![Image showing objects moving together](https://codecut.ai/wp-content/uploads/2025/11/MoveObjectsTogether_ManimCE_v0.19.0.gif)\n",
        "\n",
        "This code shows how to group objects and move them together as one unit.\n",
        "\n",
        "- **VGroup**: Groups multiple objects together so you can control them all at once (like selecting multiple items)\n",
        "- **arrange(RIGHT, buff=1)**: Lines up the objects horizontally from left to right with 1 unit of space between them\n",
        "- **shift(UP * 2)**: Moves the entire group upward by 2 units (multiplying by 2 makes it move twice as far)\n",
        "\n",
        "You can also create multiple groups and manipulate them independently or together:\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class GroupCircles(Scene):\n",
        "    def construct(self):\n",
        "        # Create circles\n",
        "        circle_green = Circle(color=GREEN)\n",
        "        circle_blue = Circle(color=BLUE)\n",
        "        circle_red = Circle(color=RED)\n",
        "\n",
        "        # Set initial positions\n",
        "        circle_green.shift(LEFT)\n",
        "        circle_blue.shift(RIGHT)\n",
        "\n",
        "        # Create 2 different groups\n",
        "        gr = VGroup(circle_green, circle_red)\n",
        "        gr2 = VGroup(circle_blue)\n",
        "        self.add(gr, gr2)\n",
        "        self.wait()\n",
        "\n",
        "        # Shift 2 groups down\n",
        "        self.play((gr + gr2).animate.shift(DOWN))\n",
        "\n",
        "        # Move only 1 group\n",
        "        self.play(gr.animate.shift(RIGHT))\n",
        "        self.play(gr.animate.shift(UP))\n",
        "\n",
        "        # Shift 2 groups to the right\n",
        "        self.play((gr + gr2).animate.shift(RIGHT))\n",
        "        self.play(circle_red.animate.shift(RIGHT))\n",
        "        self.wait()\n",
        "```\n",
        "\n",
        "\n",
        "![Image showing multiple groups of circles being manipulated](https://codecut.ai/wp-content/uploads/2025/11/GroupCircles_ManimCE_v0.19.0.gif)\n",
        "\n",
        "## Trace Path\n",
        "\n",
        "You can use `TracedPath` to create a trace of a moving object:\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class TracePath(Scene):\n",
        "    def construct(self):\n",
        "        dot = Dot(color=RED)\n",
        "\n",
        "        # Create traced path\n",
        "        path = TracedPath(dot.get_center, stroke_color=BLUE, stroke_width=4)\n",
        "        self.add(path, dot)\n",
        "\n",
        "        # Move the dot in a circular pattern\n",
        "        self.play(\n",
        "            MoveAlongPath(dot, Circle(radius=2)),\n",
        "            rate_func=linear,\n",
        "            run_time=4\n",
        "        )\n",
        "        self.wait()\n",
        "```\n",
        "\n",
        "![Image showing a trace of a moving object](https://codecut.ai/wp-content/uploads/2025/11/TracePath_ManimCE_v0.19.0.gif)\n",
        "\n",
        "This code shows how to create a trail that follows a moving object.\n",
        "\n",
        "- **Dot**: A small circular point that you can move around\n",
        "- **TracedPath(dot.get_center)**: Creates a line that draws itself following the dot's path (like a pen trail)\n",
        "- **get_center**: Gets the current position of the dot so TracedPath knows where to draw\n",
        "- **MoveAlongPath(dot, Circle(radius=2))**: Moves the dot along a circular path with radius 2\n",
        "- **rate_func=linear**: Makes the dot move at a constant speed (no speeding up or slowing down)\n",
        "- **run_time=4**: The animation takes 4 seconds to complete\n",
        "\n",
        "For a more complex example, you can create a rolling circle that traces a cycloid pattern:\n",
        "\n",
        "```python\n",
        "from manim import *\n",
        "\n",
        "class RollingCircleTrace(Scene):\n",
        "    def construct(self):\n",
        "        # Create circle and dot\n",
        "        circ = Circle(color=BLUE).shift(4*LEFT)\n",
        "        dot = Dot(color=BLUE).move_to(circ.get_start())\n",
        "\n",
        "        # Group dot and circle\n",
        "        rolling_circle = VGroup(circ, dot)\n",
        "        trace = TracedPath(circ.get_start)\n",
        "\n",
        "        # Rotate the circle\n",
        "        rolling_circle.add_updater(lambda m: m.rotate(-0.3))\n",
        "\n",
        "        # Add trace and rolling circle to the scene\n",
        "        self.add(trace, rolling_circle)\n",
        "\n",
        "        # Shift the circle to 8*RIGHT\n",
        "        self.play(rolling_circle.animate.shift(8*RIGHT), run_time=4, rate_func=linear)\n",
        "```\n",
        "\n",
        "![Image showing a rolling circle with traced path](https://codecut.ai/wp-content/uploads/2025/11/RollingCircleTrace_ManimCE_v0.19.0.gif)\n",
        "\n",
        "This code creates a rolling wheel animation that draws a curved pattern as it moves.\n",
        "\n",
        "- **Setup**: Creates a blue circle at the left side and places a blue dot at the circle's edge\n",
        "- **Grouping**: Uses `VGroup` to combine the circle and dot so they move together\n",
        "- **Path tracking**: `TracedPath` watches the circle's starting point and draws a line following it\n",
        "- **Continuous rotation**: `add_updater` makes the circle rotate automatically every frame, creating the rolling effect\n",
        "- **Rolling motion**: As the group shifts right, the rotation updater makes it look like a wheel rolling across the screen\n",
        "- **Cycloid pattern**: The traced path creates a wave-like curve showing the mathematical path a point on a rolling wheel makes\n",
        "\n",
        "## Recap\n",
        "\n",
        "Congratulations! You have just learned how to use Manim and what it can do. To recap, there are three kinds of objects that Manim provides:\n",
        "\n",
        "- **[Mobjects](https://docs.manim.community/en/stable/reference.html#mobjects)**: Objects that can be displayed on the screen, such as `Circle`, `Square`, `Matrix`, `Angle`, etc.\n",
        "- **[Scenes](https://docs.manim.community/en/stable/reference.html#scenes)**: Canvas for animations such as `Scene`, `MovingCameraScene`, etc.\n",
        "- **[Animations](https://docs.manim.community/en/stable/reference.html#animations)**: Animations applied to Mobjects such as `Write`, `Create`, `GrowFromCenter`, `Transform`, etc.\n",
        "\n",
        "There is so much more Manim can do that I cannot cover here. The best way to learn is through practice, so I encourage you to try the examples in this article and check out [Manim's tutorial](https://docs.manim.community/en/stable/tutorials/quickstart.html)."
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}